# Generated by Django 6.0 on 2026-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
