# Определяем события
events {

    worker_connections 1024; # Устанавливаем максимальное кол-во соединений
}

# Определяем основной http блок
http {
    # Помогаем браузеру правильно определить и обрабатывать разные типы файлов CSS, JS и т.д.
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Определяем сервер для django приложений
    upstream django {
        server web:8000;
    }

    # Настраиваем сервер
    server{
        listen 80; # Слушаем на порту 80
        server_name fundeploy.ru www.fundeploy.ru 150.241.94.236;

        # Определяем обработку запросов к статическим файлам
        location /static/ {
            alias /app/staticfiles/; # Указываем путь к статическим файлам в контейнере
        }

        # Проксируем остальные запросы к django приложению
        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
        }
    }
}